name: Linter

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    container:
      image:  golang:1.15.5-buster

    steps:
      - name: Install linter
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.32.2

      - name: Lint code
        run: $GOPATH/bin/golangci-lint run -e ST1006,SA1029
